"""Run every query in sql/, add 95% Wilson confidence intervals and a chi-square test,
and write one CSV per query to results/ plus a combined results/summary.md.
"""
from __future__ import annotations

import math
import sqlite3
from pathlib import Path

import pandas as pd
from scipy.stats import chi2_contingency

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "data" / "readmission.db"
SQL_DIR = ROOT / "sql"
OUT = ROOT / "results"

Z = 1.959964  # 95%


def wilson(k: int, n: int) -> tuple[float, float]:
    """Wilson score interval for a binomial proportion, in percent."""
    if n == 0:
        return (float("nan"), float("nan"))
    p = k / n
    denom = 1 + Z**2 / n
    centre = (p + Z**2 / (2 * n)) / denom
    half = Z * math.sqrt(p * (1 - p) / n + Z**2 / (4 * n**2)) / denom
    return round(100 * (centre - half), 2), round(100 * (centre + half), 2)


def main() -> None:
    OUT.mkdir(exist_ok=True)
    con = sqlite3.connect(DB)
    lines = ["# Results\n", "Generated by `src/02_run_analysis.py` from `data/readmission.db`.\n"]

    for path in sorted(SQL_DIR.glob("*.sql")):
        sql = path.read_text()
        title = next((l[3:].strip() for l in sql.splitlines() if l.startswith("--")), path.stem)
        df = pd.read_sql_query(sql, con)

        test_note = ""
        if {"n", "readmit_30"}.issubset(df.columns):
            cis = [wilson(int(k), int(n)) for k, n in zip(df["readmit_30"], df["n"])]
            df["ci95_low"] = [c[0] for c in cis]
            df["ci95_high"] = [c[1] for c in cis]
            if len(df) > 1 and "no-test" not in sql:
                table = [[int(k), int(n - k)] for k, n in zip(df["readmit_30"], df["n"])]
                chi2, p, dof, _ = chi2_contingency(table)
                p_txt = "< 0.001" if p < 0.001 else f"{p:.3f}"
                test_note = f"Chi-square test of independence: χ² = {chi2:.1f}, df = {dof}, p {p_txt if p_txt.startswith('<') else '= ' + p_txt}"
                df.attrs["chi2"], df.attrs["p"] = chi2, p

        df.to_csv(OUT / f"{path.stem}.csv", index=False)
        lines.append(f"\n## {title}\n")
        lines.append(df.to_markdown(index=False))
        if test_note:
            lines.append(f"\n\n{test_note}")
        lines.append("\n")
        print(f"{path.name:<36} {len(df):>3} rows  {test_note}")

    dq = pd.read_sql_query("SELECT * FROM dq_log ORDER BY step", con)
    dq.to_csv(OUT / "00_cleaning_log.csv", index=False)
    lines.insert(2, "\n## Cleaning log\n\n" + dq.to_markdown(index=False) + "\n")
    (OUT / "summary.md").write_text("\n".join(lines))
    con.close()


if __name__ == "__main__":
    main()
